### ISSUE TITLE
Un moyen de paralléliser le problème ?

### ISSUE THREAD

**Issue by lebarde** [scienceetonnante/WordleSutom#9]
Bonjour à tous et bonjour David,
Pour le moment ça prend du temps sur mon core i5 9500 (j'éditerai pour donner le temps).

Comment est-ce qu'on pourrait faire, dans l'absolu, pour paralléliser les calculs ? Je sais qu'en Go, par exemple, il y a un mécanisme simple pour le faire...

**Comment by kay0u** [comment]
Should be done in #10
